services:
  frontend:
    build:
      dockerfile: Dockerfile
      context: frontend/
    ports:
      - "80:3000"
  backend:
    build:
      dockerfile: Dockerfile
      context: backend/
    ports:
      - "5000:5000"